import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import APOD from '../components/sections/apod/APOD'
import NASAService from '../API/NASAService'
import { IAPOD } from '../types/APOD'

const Home: NextPage<{
        apod: IAPOD
      }> = ({ apod }) => {
  return (
    <>
      <Head>
        <title>Space Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <APOD
        data={apod}
      >
        <Header/>
      </APOD>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await NASAService.getAPOD();

  return {
    props: {
      apod: data
    }
  }
}

export default Home;
