import Head from "next/head";
import { FC } from "react";
import Header from "../header/Header";

type Props = {
    children: React.ReactNode
}

const Layout: FC<Props> = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Space Blog App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            { children }
        </div>
    );
} 
export default Layout;